### ISSUE TITLE
Source directory does not exist.

### ISSUE THREAD

**Issue by Gouthamprashanth** [labbots/firestore-export-json#5]
I'm trying to convert the firebase output-0 file to json
I used this code as u mentioned in the git

fs_to_json source/output-0 -d ~/Documents/firebase-export.json

but i'm getting this error.

Source directory does not exist.
![Screenshot from 2021-06-18 08-32-41](https://user-images.githubusercontent.com/80561429/122662999-e1f23f00-d1b4-11eb-8225-1eea58b3fba3.png)

**Comment by ryaminal** [comment]
source_dir should be a directory, not a file. try `fs_to_json source -d ~/Documents/firebase-export.json`
the script will iterate over everything in the `source` dir that starts with `output-`.

**Comment by Gouthamprashanth** [comment]
It Worked,
Thanks.
